### PR TITLE
Composer 2 support

### PR DESCRIPTION
**Pull request by greg-1-anderson**
Re-opening #34 so that I can merge hussainweb#1 to get tests to run and hopefully green.

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
@derhasi Could you please merge this PR and tag a new release for Composer 2 support? Thank you.

**Comment by greg-1-anderson** [comment]
This PR is nearly identical to #34, but I prefer this version.

**Comment by paul-m** [comment]
+1 would love to get Composer 2 happening for this project.

**Comment by greg-1-anderson** [comment]
@webflo Could you help out here, perhaps?  Or @derhasi, ping # 2.

**Comment by webflo** [comment]
Thanks for your work!

**Pull request merged**
